---
# Source: ingress-nginx/templates/controller-service.yaml
apiVersion: v1
kind: Service
metadata:
  name: release-name-ingress-nginx-controller
  namespace: default
spec:
  ports:
    - name: zzzzzz
      port: 80
      protocol: TCP
      targetPort: http
      appProtocol: http